#!/usr/bin/python -W ignore::DeprecationWarning
# -*- encoding: utf-8 -*-

from icalendar import Calendar, Event, UTC
from datetime import datetime
import tempfile, os, sys, getopt

class Cours:
    def __init__(self):
        pass
class Heure:
    def __init__(self,h,m):
        self.h = int(h)
        self.m = int(m)

class Heures:
    def __init__(self, h1, h2):
        tmp1 = h1.split(":")
        tmp2 = h2.split(":")
        self.start = Heure(tmp1[0], tmp1[1])
        self.end = Heure(tmp2[0], tmp2[1])

class Date:
    def __init__(self,d,m,y):
        self.d = int(d)
        self.m = int(m)
        self.y = int(y)

def parse(fichier):
    cours = []
    c = Cours()
    dernier_jour = ""
    prof = ""

    for ligne in fichier:
        ligne_cours = ligne.split("<u>")
        ligne_prof = ligne.split('<td width="30%" valign="top" align="center">')
        ligne_local = ligne.split('<td width="20%" valign="top" align="center">')
        ligne_date = ligne.split('<b>')
        ligne_heure = ligne.split('<td class="jour" height="40" align="center" width="15%" valign="top">')
        ligne_type = ligne.split('<br />')

        if len(ligne_date) == 2:
            tmp = ligne_date[1].split('</b>\n')[0]
            if len(tmp.split(" ")) == 2:
                tmp = tmp.split(" ")
                date = tmp[1].split("/")
                if len(date) == 3:
                    #possibilité d'avoir le jour avec tmp[0]
                    date = tmp[1].split("/")
                    dernier_jour = Date(date[0], date[1], date[2])
        elif len(ligne_heure) == 2:
            heure = ligne_heure[1].split('\n')[0]
            heures = heure.split("-")
            c.heures = Heures(heures[0], heures[1])
        elif len(ligne_type) == 2:
            tmp = ligne_type[1].split('</td>\n')
            if len(tmp) == 2 and not tmp[1] and tmp[0]:
                if len(tmp[0]) == 4:
                    c.type = tmp[0]
                else:
                     #mauvais formatage des horaires
                     prof = tmp[0]
        elif len(ligne_cours) == 2:
            nom = ligne_cours[1].split('</u>')[0]
            c.cours = nom
        elif len(ligne_prof) == 2:
            tmp = ligne_prof[1].split('</td>\n')
            tmp = tmp[0].split('\n')
            c.prof = tmp[0]
            prof = ""
        elif len(ligne_local) == 2:
            ligne_local = ligne_local[1].split('</td')
            c.salle = ligne_local[0]
            c.jour = dernier_jour
            if prof:
                c.prof = prof + " - " + c.prof
            cours.append(c)
            c = Cours()
    return cours

def construct_cal(cours):
    cal = Calendar()
    cal.add('prodid', "My cal")
    cal.add('version', "0.1")

    lessons = list(set(map((lambda c: c.type + " - " + c.cours), cours)))
    ids = range(len(lessons))
    dico = dict(zip(lessons,ids))

    for c in cours:
        if not (dico[c.type + " - " + c.cours] in ids_to_delete):
            event = Event()
            event.add('summary', c.type + " - " + c.cours)
            d = c.date
            h = c.heures.start
            event.add('dtstart', datetime(d.y, d.m, d.d,
                                          h.h, h.m, 0))
            h = c.heures.end
            event.add('dtend',datetime(d.y, d.m, d.d,
                                       h.h, h.m, 0))
            event.add('organizer', c.prof)
            event.add('location', c.salle)
            cal.add_component(event)
    return cal

def main():
    fichier = open(file)
    cours = parse(fichier)
    if only_show_lessons:
        lessons = list(set(map((lambda c: c.type + " - " + c.cours), cours)))
        for i, lesson in enumerate(lessons):
            print i, ")", lesson
    else:
        cal = construct_cal(cours)
        directory = tempfile.mkdtemp()
        f = open(output, 'wb')
        f.write(cal.as_string())
        f.close()


def usage():
    print ""
    print "Usage: parser [OPTIONS]"
    print ""
    print "\t-h, --help\t\tShow help message and exit"
    print "\t-l, --list\t\tList all the Lessons with their ID, conflicts with -o and -F"
    print "\t-F, --filter\tparser -f 1-4-5 delete lessons with ID 1,4 and 5"
    print "\t-f, --file\t\tpath to the html file"
    print "\t-o, --output\tpath to the ics file to render, if not specified, write in the cal.ics file, in the current directory"

if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hlf:F:o:",
                                   ["help", "list", "filter","file","output"])
    except getopt.GetoptError, err:
        print str(err)
        usage()
        sys.exit(2)
    global only_show_lessons
    global ids
    global file
    global output
    only_show_lessons = False
    ids_to_delete = []
    file = ""
    output = "cal.ics"
    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit(0)
        elif o in ("-l", "--list"):
            only_show_lessons = True
        elif o in ("-F", "--filter"):
            ids_to_delete = map(int,a.split("-"))
        elif o in ("-f", "--file"):
            file = a
        elif o in ("-o", "--output"):
            output = a
        else:
            assert False, "unhandled option"
    if file:
        #main()
        cours = parse(open(file))
        for c in cours:
            #print c.prof
            #print c.salle
            #print c.jour.d
            #print c.heures.start.h, c.heures.start.m
            print c.prof
            #print c.cours
            #pass
    else:
        print "need an input file, type --help or -h for help"
        sys.exit(0)
